spring:
  # boot:
  #   admin:
  #     client:
  #       url: http://localhost:10000
  application:
    name: api-authorization
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:authorization;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
api:
  security:
    token:
      secret: ${JWT_SECRET:this_is_my_super_secure_secret_key_123!}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

springdoc:
  details:
    security-header: Authorization
    description: Bearer + Token JWT
    title: User authorization API
    version: v1
  swagger-ui:
    path: /v1/authorization/swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    url: /v1/authorization/api-docs
  api-docs:
    path: /v1/authorization/api-docs


# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"