services:

  infra-analytics: # Spring Boot Admin
    build: ./infra-analytics
    ports:
      - "10000:10000"
    networks: [backend]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://infra-analytics:10000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  infra-discovery: # Eureka
    build: ./infra-discovery
    ports:
      - "8761:8761"
    networks: [backend]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://infra-discovery:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  infra-gateway: # Spring Cloud Gateway
    build: ./infra-gateway
    ports:
      - "80:80"
    networks: [backend]
    depends_on:
      infra-discovery:
        condition: service_healthy
      infra-analytics:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://infra-discovery:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      # SCG discovery locator
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID: "true"
      # Spring Boot Admin
      SPRING_BOOT_ADMIN_CLIENT_URL: http://infra-analytics:10000
      # Keycloak config (match your Keycloak realm & client)
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:11000/realms/myrealm
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: gateway
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: mysecret

  keycloak: # Keycloak server
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "11000:11000" # host:container (11000 on host, 11000 in container)
    networks: [backend]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  backend:
    driver: bridge