# application.yml
server:
  port: 80
spring:
  application:
    name: infra-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: my-api-id-here
          uri: lb://MY_API_HERE # Put here the target ms service
          predicates:
            - Path=/v1/**, /auth/**, /api/**, /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /springdoc/**
        - id: unmapped-request
          uri: lb://unmapped-request
          predicates:
              - Path=/unmapped-request/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    com.netflix.discovery: TRACE
    com.netflix.eureka: TRACE
    org.springframework.cloud.netflix.eureka: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always